'use client';
import { FormEvent, useMemo, useState } from 'react';
import { api } from '../lib/api';
import { Mascot } from './Mascot';
import { ProgressStepper } from './ProgressStepper';

const steps = ['Welcome', 'About you', 'Work details', 'Review'];
const about = [['nameAndSurname', 'Name and surname'], ['privateEmail', 'Personal email'], ['country', 'Country']] as const;
const work = [['department', 'Department'], ['jobPosition', 'Job position']] as const;
const initial = Object.fromEntries([...about, ...work, ['githubProfile', ''], ['githubRepos', '']].map(([key]) => [key, '']));
const emailFields = new Set(['privateEmail', 'managerEmail', 'emailAddress']);
const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const stepForField = (key: string) => about.some(([name]) => name === key) ? 1 : 2;

export function OnboardingWizard() {
  const [step, setStep] = useState(0); const [values, setValues] = useState<Record<string, string>>(initial);
  const [errors, setErrors] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false); const [submitted, setSubmitted] = useState<string | null>(null);
  const development = ['dev', 'development'].includes(values.department.trim().toLowerCase());
  const activeFields = useMemo(() => step === 1 ? about.map(([name]) => name) : step === 2 ? [...work.map(([name]) => name), ...(development ? ['githubProfile', 'githubRepos'] : [])] : [], [step, development]);
  const setValue = (name: string, value: string) => setValues(current => ({ ...current, [name]: value }));
  function validate(fields: readonly string[]) { const next: Record<string, string> = {}; for (const name of fields) { if (!values[name]?.trim()) next[name] = 'This field is required.'; else if (emailFields.has(name) && !emailPattern.test(values[name])) next[name] = 'Enter a valid email address.'; } setErrors(current => ({ ...current, ...next })); return next; }
  function advance() { const next = validate(activeFields); if (Object.keys(next).length === 0) { setErrors({}); setStep(current => Math.min(current + 1, 3)); } }
  async function submit(event: FormEvent) { event.preventDefault(); const next = validate([...about.map(([name]) => name), ...work.map(([name]) => name), ...(development ? ['githubProfile', 'githubRepos'] : [])]); if (Object.keys(next).length) { setStep(stepForField(Object.keys(next)[0])); return; } setBusy(true); setErrors({}); try { const result = await api.submit(values); setSubmitted(result.requestCode); } catch (error: unknown) { const body = error as { errors?: Record<string, string>; error?: string }; const serverErrors = body.errors || { form: body.error || 'We could not submit your information. Please try again.' }; setErrors(serverErrors); const first = Object.keys(serverErrors).find(key => key !== 'form'); if (first) setStep(stepForField(first)); } finally { setBusy(false); } }
  const input = (name: string, label: string, multiline = false) => <label className="field" key={name}><span>{label}</span>{multiline ? <textarea value={values[name]} onChange={event => setValue(name, event.target.value)} aria-invalid={Boolean(errors[name])} aria-describedby={errors[name] ? `${name}-error` : undefined} placeholder="One per line or comma-separated" /> : <input type={emailFields.has(name) ? 'email' : 'text'} value={values[name]} onChange={event => setValue(name, event.target.value)} aria-invalid={Boolean(errors[name])} aria-describedby={errors[name] ? `${name}-error` : undefined} />}{errors[name] && <small id={`${name}-error`}>{errors[name]}</small>}</label>;
  if (submitted) return <main className="onboarding-page"><section className="onboarding-card success-card"><div><span className="eyebrow">ONBOARDLY</span><h1>You’re all set.</h1><p>Your onboarding information is with the team. We’ll email your account details once your request has been processed.</p><code>{submitted}</code><button onClick={() => { setValues(initial); setSubmitted(null); setStep(0); }}>Submit another request</button></div><Mascot mood="celebrate" /></section></main>;
  return <main className="onboarding-page"><section className="onboarding-card"><div className="wizard-main"><span className="eyebrow">ONBOARDLY · EMPLOYEE ONBOARDING</span><ProgressStepper step={step} labels={steps} />
    {step === 0 && <div className="wizard-copy"><span className="welcome-pill">A few minutes, one smooth start</span><h1>Let’s get you ready for day one.</h1><p>Share a few details and we’ll prepare your account request for review. You can go back at any time.</p><button onClick={advance}>Let’s begin <span aria-hidden="true">→</span></button></div>}
    {step === 1 && <form onSubmit={event => { event.preventDefault(); advance(); }}><div className="wizard-copy"><h1>First, tell us about you.</h1><p>We’ll use your personal email to send your account instructions.</p></div><div className="field-grid">{about.map(([name, label]) => input(name, label))}</div><div className="wizard-actions"><button className="quiet-button" type="button" onClick={() => setStep(0)}>Back</button><button>Continue <span aria-hidden="true">→</span></button></div></form>}
    {step === 2 && <form onSubmit={event => { event.preventDefault(); advance(); }}><div className="wizard-copy"><h1>Now for your work details.</h1><p>This helps the team prepare the right setup for your request.</p></div><div className="field-grid">{work.map(([name, label]) => input(name, label))}{development && <><div className="field-note">Development request detected — add your GitHub details below.</div>{input('githubProfile', 'GitHub profile link or name')}{input('githubRepos', 'GitHub repositories to add', true)}</>}</div><div className="wizard-actions"><button className="quiet-button" type="button" onClick={() => setStep(1)}>Back</button><button>Continue <span aria-hidden="true">→</span></button></div></form>}
    {step === 3 && <form onSubmit={submit}><div className="wizard-copy"><h1>One last check.</h1><p>Make sure everything looks right before you send your request.</p></div><div className="review-list">{[['About you', about, 1], ['Work details', [...work, ...(development ? [['githubProfile', 'GitHub profile link or name'], ['githubRepos', 'GitHub repositories to add']] : [])], 2]].map(([title, fields, target]) => <section key={String(title)}><div className="review-heading"><h2>{String(title)}</h2><button type="button" className="text-button" onClick={() => setStep(Number(target))}>Edit</button></div>{(fields as readonly (readonly string[])[]).map(([name, label]) => <div className="review-row" key={name}><span>{label}</span><strong>{values[name]}</strong></div>)}</section>)}</div>{errors.form && <p className="form-error">{errors.form}</p>}<div className="wizard-actions"><button className="quiet-button" type="button" onClick={() => setStep(2)}>Back</button><button disabled={busy}>{busy ? 'Sending request…' : 'Submit onboarding request'}</button></div></form>}
  </div><aside className="wizard-aside"><Mascot mood={step === 0 ? 'idle' : 'progress'} /><div><span className="eyebrow">YOUR ONBOARDING GUIDE</span><h2>{step === 0 ? 'A simple start.' : step === 3 ? 'Almost there!' : 'You’re doing great.'}</h2><p>{step === 0 ? 'Four clear steps. Your details stay with the onboarding team.' : 'Your progress is saved on this page while you complete the form.'}</p></div></aside></section></main>;
}
