/**
 * Workflow statuses (PRD section 16).
 *
 * INVITED and FORM_OPENED are reserved for the future invitation-link flow
 * (PRD section 6); the MVP's direct-submission flow starts at SUBMITTED.
 */
export const STATUS = Object.freeze({
  INVITED: 'INVITED',
  FORM_OPENED: 'FORM_OPENED',
  SUBMITTED: 'SUBMITTED',
  PENDING_REVIEW: 'PENDING_REVIEW',
  APPROVED: 'APPROVED',
  PROVISIONING: 'PROVISIONING',
  ACCOUNT_CREATED: 'ACCOUNT_CREATED',
  NOTIFICATION_SENT: 'NOTIFICATION_SENT',
  COMPLETED: 'COMPLETED',

  REJECTED: 'REJECTED',
  RETURNED: 'RETURNED',
  PROVISIONING_FAILED: 'PROVISIONING_FAILED',
  PARTIALLY_PROVISIONED: 'PARTIALLY_PROVISIONED',
  CANCELLED: 'CANCELLED',
});

export const ACTIVE_QUEUE_STATUSES = [STATUS.PENDING_REVIEW, STATUS.APPROVED];

export const FAILED_QUEUE_STATUSES = [STATUS.PROVISIONING_FAILED, STATUS.PARTIALLY_PROVISIONED];

export const TERMINAL_STATUSES = [STATUS.COMPLETED, STATUS.REJECTED, STATUS.CANCELLED];
